const fs = require("node:fs");
const path = require("node:path");
const ts = require("typescript");

const filePath = path.join(__dirname, "..", "src", "data", "seedFlashcards.ts");
const sourceText = fs.readFileSync(filePath, "utf8");
const sourceFile = ts.createSourceFile(
  filePath,
  sourceText,
  ts.ScriptTarget.Latest,
  true,
);

const targetFields = new Set([
  "question",
  "answer",
  "theme",
  "area",
  "source",
  "notes",
]);

const replacements = new Map(
  Object.entries({
    "1a": "1ª",
    "1o": "1º",
    acao: "ação",
    acido: "ácido",
    acido: "ácido",
    acido: "ácido",
    acu: "acu",
    aguda: "aguda",
    alem: "além",
    alergeno: "alérgeno",
    analgesico: "analgésico",
    aneis: "anéis",
    antibiotica: "antibiótica",
    antibioticas: "antibióticas",
    antibiotico: "antibiótico",
    antibioticos: "antibióticos",
    antihipertensivos: "anti-hipertensivos",
    anticolinergico: "anticolinérgico",
    antitermico: "antitérmico",
    apos: "após",
    apropriadas: "apropriadas",
    arritmias: "arritmias",
    articulacao: "articulação",
    articulacoes: "articulações",
    asmatica: "asmática",
    atencao: "atenção",
    ate: "até",
    atipicos: "atípicos",
    avaliacao: "avaliação",
    basica: "básica",
    basicas: "básicas",
    bocio: "bócio",
    cabeca: "cabeça",
    calcio: "cálcio",
    cardiaca: "cardíaca",
    cardiaco: "cardíaco",
    cardiacos: "cardíacos",
    cenario: "cenário",
    cenarios: "cenários",
    cetoprofeno: "cetoprofeno",
    clamidia: "clamídia",
    classico: "clássico",
    clinica: "clínica",
    clinicas: "clínicas",
    clinico: "clínico",
    clinicos: "clínicos",
    colecao: "coleção",
    combinacao: "combinação",
    coinfeccao: "coinfecção",
    codeina: "codeína",
    contraindicacao: "contraindicação",
    contraindicacoes: "contraindicações",
    contraindicados: "contraindicados",
    corticoide: "corticoide",
    corticoides: "corticoides",
    cranio: "crânio",
    crianca: "criança",
    criancas: "crianças",
    cronica: "crônica",
    cronicas: "crônicas",
    cronico: "crônico",
    da: "da",
    decubito: "decúbito",
    dependencia: "dependência",
    depressao: "depressão",
    descompensacao: "descompensação",
    desidratacao: "desidratação",
    diagnostica: "diagnóstica",
    diagnostico: "diagnóstico",
    diarreia: "diarreia",
    diferenca: "diferença",
    diferencas: "diferenças",
    dificil: "difícil",
    dilatacao: "dilatação",
    disponivel: "disponível",
    doencas: "doenças",
    duracao: "duração",
    eletronica: "eletrônica",
    eletrica: "elétrica",
    emergencia: "emergência",
    encefalopatia: "encefalopatia",
    endocrinologia: "Endocrinologia",
    esteroides: "esteroides",
    estreptococica: "estreptocócica",
    etaria: "etária",
    evolucao: "evolução",
    exacerbacoes: "exacerbações",
    exacerbacao: "exacerbação",
    frequencia: "frequência",
    funcao: "função",
    gastrica: "gástrica",
    gestacao: "gestação",
    gravidas: "grávidas",
    glicemico: "glicêmico",
    hemorragia: "hemorragia",
    hepatica: "hepática",
    hepatopatia: "hepatopatia",
    hipermagnesemia: "hipermagnesemia",
    hipertensao: "hipertensão",
    hipoglicemico: "hipoglicêmico",
    historia: "história",
    ileocecal: "ileocecal",
    iliaca: "ilíaca",
    iliaco: "ilíaco",
    infeccao: "infecção",
    infeccoes: "infecções",
    inflamacao: "inflamação",
    inflamatorios: "inflamatórios",
    inalatorio: "inalatório",
    inicio: "início",
    insuficiencia: "insuficiência",
    interacoes: "interações",
    irritacao: "irritação",
    lactamica: "lactâmica",
    lactamicos: "lactâmicos",
    lagrimas: "lágrimas",
    lesao: "lesão",
    lesoes: "lesões",
    liquido: "líquido",
    macrolideo: "macrolídeo",
    macrolideos: "macrolídeos",
    manutencao: "manutenção",
    maxima: "máxima",
    medico: "médico",
    mnemomico: "mnemônico",
    monoterapia: "monoterapia",
    musculo: "músculo",
    musculos: "músculos",
    necessario: "necessário",
    nefroprotecao: "nefroproteção",
    niveis: "níveis",
    no: "no",
    nodulos: "nódulos",
    numero: "número",
    obstetricia: "obstetrícia",
    obstrucao: "obstrução",
    oligoidramnio: "oligoidrâmnio",
    opcao: "opção",
    opcoes: "opções",
    orgao: "órgão",
    ossea: "óssea",
    osseo: "ósseo",
    patologicos: "patológicos",
    patogenos: "patógenos",
    pediatrica: "pediátrica",
    pediatrico: "pediátrico",
    pe: "pé",
    penicilina: "penicilina",
    periconcepcional: "periconcepcional",
    periodo: "período",
    perfusao: "perfusão",
    pratica: "prática",
    praticas: "práticas",
    precoce: "precoce",
    pre: "pré",
    prenat: "prenat",
    pressao: "pressão",
    prevencao: "prevenção",
    possivel: "possível",
    proximo: "próximo",
    producao: "produção",
    profilatica: "profilática",
    protons: "prótons",
    quadril: "quadril",
    reagir: "reagir",
    rapido: "rápido",
    reacao: "reação",
    receptores: "receptores",
    recem: "recém",
    recaptacao: "recaptação",
    reducao: "redução",
    retencao: "retenção",
    regiao: "região",
    respiracao: "respiração",
    respiratoria: "respiratória",
    respiratorio: "respiratório",
    responsavel: "responsável",
    restrita: "restrita",
    retenção: "retenção",
    salicilatos: "salicilatos",
    saturacao: "saturação",
    saude: "saúde",
    sedacao: "sedação",
    selecao: "seleção",
    sensacao: "sensação",
    servico: "serviço",
    sindrome: "síndrome",
    situacao: "situação",
    situacoes: "situações",
    sodio: "sódio",
    subcutaneo: "subcutâneo",
    suplementacao: "suplementação",
    sustentacao: "sustentação",
    tambem: "também",
    tecnica: "técnica",
    terapeutica: "terapêutica",
    terapeutico: "terapêutico",
    terapeuticos: "terapêuticos",
    tolerancia: "tolerância",
    tinea: "tínea",
    topica: "tópica",
    topico: "tópico",
    transitoria: "transitória",
    trigemeo: "trigêmeo",
    trombotico: "trombótico",
    unica: "única",
    urinaria: "urinária",
    urinarias: "urinárias",
    ulcera: "úlcera",
    util: "útil",
    vacinacao: "vacinação",
    varias: "várias",
    variavel: "variável",
    acumulo: "acúmulo",
    agregacao: "agregação",
    agua: "água",
    alteracoes: "alterações",
    alveolos: "alvéolos",
    aereas: "aéreas",
    agitacao: "agitação",
    confusao: "confusão",
    eliminacao: "eliminação",
    erosao: "erosão",
    filtracao: "filtração",
    generico: "genérico",
    geracao: "geração",
    gastrico: "gástrico",
    hidratacao: "hidratação",
    incisao: "incisão",
    liberacao: "liberação",
    nitrofurantoina: "nitrofurantoína",
    orientacao: "orientação",
    pulmao: "pulmão",
    serotoninergica: "serotoninérgica",
    urticaria: "urticária",
    anatomica: "anatômica",
    aerobios: "aeróbios",
    alimentacao: "alimentação",
    anaerobios: "anaeróbios",
    apresentacao: "apresentação",
    arteriola: "arteríola",
    atopicos: "atópicos",
    autonomica: "autonômica",
    broncoconstricao: "broncoconstrição",
    cacifo: "cacifo",
    caido: "caído",
    colageno: "colágeno",
    coloracao: "coloração",
    coluria: "colúria",
    comorbidos: "comórbidos",
    congestao: "congestão",
    confirmatorio: "confirmatório",
    congruencia: "congruência",
    contem: "contém",
    contusao: "contusão",
    convulsoes: "convulsões",
    cutanea: "cutânea",
    dentaria: "dentária",
    diaria: "diária",
    dorsiflexao: "dorsiflexão",
    esofago: "esôfago",
    estrogenio: "estrogênio",
    evacuacoes: "evacuações",
    espacador: "espaçador",
    especifica: "específica",
    folico: "fólico",
    foliculos: "folículos",
    formacao: "formação",
    formula: "fórmula",
    glandulas: "glândulas",
    hipocondrio: "hipocôndrio",
    hipoperfusao: "hipoperfusão",
    hipotensao: "hipotensão",
    ictericia: "icterícia",
    imprevisiveis: "imprevisíveis",
    insonia: "insônia",
    intoxicacao: "intoxicação",
    intubacao: "intubação",
    ipratropio: "ipratrópio",
    lactica: "láctica",
    linfatica: "linfática",
    luxacao: "luxação",
    mantem: "mantém",
    nauseas: "náuseas",
    nivel: "nível",
    odontologico: "odontológico",
    oftalmico: "oftálmico",
    oliguria: "oligúria",
    oxigenio: "oxigênio",
    padrao: "padrão",
    palpebras: "pálpebras",
    peptica: "péptica",
    penetracao: "penetração",
    perfuracao: "perfuração",
    plaquetaria: "plaquetária",
    polifarmacia: "polifarmácia",
    preocupacao: "preocupação",
    primaria: "primária",
    proliferacao: "proliferação",
    reidratacao: "reidratação",
    recomendacoes: "recomendações",
    repeticao: "repetição",
    respiratorias: "respiratórias",
    respiratorios: "respiratórios",
    resistencia: "resistência",
    reumatica: "reumática",
    reversivel: "reversível",
    saida: "saída",
    sistemico: "sistêmico",
    sintomatica: "sintomática",
    superficies: "superfícies",
    tetano: "tétano",
    triciclicos: "tricíclicos",
    vulneravel: "vulnerável",
    visuais: "visuais",
    vomitos: "vômitos",
  }),
);

const phraseReplacements = [
  [/Qual e\b/g, "Qual é"],
  [/\be administrad([ao])\b/g, "é administrad$1"],
  [/\be aplicad([ao])\b/g, "é aplicad$1"],
  [/\be contraindicad([ao]s?)\b/g, "é contraindicad$1"],
  [/\be esperad([ao])\b/g, "é esperad$1"],
  [/\be feita\b/g, "é feita"],
  [/\be feito\b/g, "é feito"],
  [/\be indicada\b/g, "é indicada"],
  [/\be indicado\b/g, "é indicado"],
  [/\be obrigatoria\b/g, "é obrigatória"],
  [/\be o principal\b/g, "é o principal"],
  [/\be restrita\b/g, "é restrita"],
  [/\be usado\b/g, "é usado"],
  [/\be usada\b/g, "é usada"],
  [/\be usado\b/g, "é usado"],
  [/\bA ideia e\b/g, "A ideia é"],
  [/\bO objetivo e\b/g, "O objetivo é"],
  [/\bO regime e\b/g, "O regime é"],
  [/\bA formula aproximada e\b/g, "A fórmula aproximada é"],
  [/\bO minimo e\b/g, "O mínimo é"],
  [/\bO tratamento principal e\b/g, "O tratamento principal é"],
  [/\bO alvo principal e\b/g, "O alvo principal é"],
  [/\bO motivo e\b/g, "O motivo é"],
  [/\bO metabolismo via CYP2D6 e\b/g, "O metabolismo via CYP2D6 é"],
  [/\bAnlodipino e comum\b/g, "Anlodipino é comum"],
  [/\bNo primeiro trimestre e repetido\b/g, "No primeiro trimestre é repetido"],
  [/\bE o padrao-ouro\b/g, "É o padrão-ouro"],
  [/\bE uma cefalosporina\b/g, "É uma cefalosporina"],
  [/\bE uma opção\b/g, "É uma opção"],
  [/\bCefalexina e uma alternativa\b/g, "Cefalexina é uma alternativa"],
  [/\bMetformina\. E a principal\b/g, "Metformina. É a principal"],
  [/\bE importante\b/g, "É importante"],
  [/\bE testado\b/g, "É testado"],
  [/\bE vulneravel\b/g, "É vulnerável"],
  [/\bO ideal e\b/g, "O ideal é"],
  [/\bo ideal e\b/g, "o ideal é"],
  [/\bQual suplemento e mais importante\b/g, "Qual suplemento é mais importante"],
  [/\bO risco e classico\b/g, "O risco é clássico"],
  [/\bO risco e clássico\b/g, "O risco é clássico"],
  [/\bEsta associada\b/g, "Está associada"],
  [/\bTraqueia e anterior\b/g, "Traqueia é anterior"],
  [/\bEsofago e posterior\b/g, "Esôfago é posterior"],
  [/\bUma formula aproximada e\b/g, "Uma fórmula aproximada é"],
  [/\bQual nervo e responsável\b/g, "Qual nervo é responsável"],
  [/\bbaixas doses e evitada\b/g, "baixas doses é evitada"],
  [/\bpulmão e descompensação\b/g, "pulmão é descompensação"],
  [/\bpulmao e descompensacao\b/g, "pulmão é descompensação"],
  [/\bque mantém a dilatação\b/g, "que mantêm a dilatação"],
  [/\b2a geracao\b/g, "2ª geração"],
  [/\b2a geração\b/g, "2ª geração"],
  [/\bA profilaxia e\b/g, "A profilaxia é"],
  [/\bFratura e\b/g, "Fratura é"],
  [/\bLuxacao e\b/g, "Luxação é"],
  [/\bEntorse e\b/g, "Entorse é"],
  [/\bContusao e\b/g, "Contusão é"],
  [/\bHematoma e\b/g, "Hematoma é"],
  [/\bUrticaria sao\b/g, "Urticária são"],
  [/\bAngioedema e\b/g, "Angioedema é"],
  [/\bEczema e\b/g, "Eczema é"],
  [/\bDermatite de contato e\b/g, "Dermatite de contato é"],
  [/\bDispneia e\b/g, "Dispneia é"],
  [/\bTaquipneia e\b/g, "Taquipneia é"],
  [/\bHipotensao e\b/g, "Hipotensão é"],
  [/\bChoque e\b/g, "Choque é"],
  [/\bEdema e\b/g, "Edema é"],
  [/\bLinfedema ocorre\b/g, "Linfedema ocorre"],
  [/\bErosao e\b/g, "Erosão é"],
  [/\bUlcera atinge\b/g, "Úlcera atinge"],
  [/\bSincope e\b/g, "Síncope é"],
  [/\bPre-sincope e\b/g, "Pré-síncope é"],
  [/\bGastrite e\b/g, "Gastrite é"],
  [/\bUlcera e\b/g, "Úlcera é"],
  [/\bHipertensao e\b/g, "Hipertensão é"],
  [/\bArtrite e\b/g, "Artrite é"],
  [/\bArtrose e\b/g, "Artrose é"],
  [/\bConvulsao e\b/g, "Convulsão é"],
  [/\bEpilepsia e\b/g, "Epilepsia é"],
  [/\bCelulite acomete\b/g, "Celulite acomete"],
  [/\bErisipela e\b/g, "Erisipela é"],
  [/\bDiarreia e\b/g, "Diarreia é"],
  [/\bDisenteria e\b/g, "Disenteria é"],
  [/\bIctericia e\b/g, "Icterícia é"],
  [/\bColestase e\b/g, "Colestase é"],
  [/\bInsuficiencia cardiaca e\b/g, "Insuficiência cardíaca é"],
  [/\bHipoglicemia e\b/g, "Hipoglicemia é"],
  [/\bChoque hipoglicemico e\b/g, "Choque hipoglicêmico é"],
  [/\bSao\b/g, "São"],
  [/\bsao\b/g, "são"],
  [/\bNao\b/g, "Não"],
  [/\bnao\b/g, "não"],
  [/\bha\b/g, "há"],
  [/\bHa\b/g, "Há"],
  [/\bpos-infarto\b/g, "pós-infarto"],
  [/\bpre-natal\b/g, "pré-natal"],
  [/\bPre-natal\b/g, "Pré-natal"],
  [/\bpre-escolar\b/g, "pré-escolar"],
  [/\bre em/g, "re em"],
];

const preserveCase = (original, replacement) => {
  if (original === original.toUpperCase()) return replacement.toUpperCase();
  if (original[0] === original[0].toUpperCase()) {
    return replacement[0].toUpperCase() + replacement.slice(1);
  }
  return replacement;
};

const accentText = (value) => {
  let next = value;

  for (const [pattern, replacement] of phraseReplacements) {
    next = next.replace(pattern, replacement);
  }

  for (const [plain, accented] of replacements) {
    next = next.replace(
      new RegExp(`\\b${plain}\\b`, "gi"),
      (match) => preserveCase(match, accented),
    );
  }

  next = next
    .replace(/\bRecém-nascido\b/g, "recém-nascido")
    .replace(/\bPré-natal\b/g, "Pré-natal")
    .replace(/\bGinecologia e Obstetrícia\b/g, "Ginecologia e obstetrícia")
    .replace(/\bDiretrizes clínicas\b/g, "Diretrizes clínicas");

  return next;
};

const edits = [];

const visit = (node) => {
  if (
    ts.isPropertyAssignment(node) &&
    ts.isIdentifier(node.name) &&
    targetFields.has(node.name.text) &&
    (ts.isStringLiteral(node.initializer) ||
      ts.isNoSubstitutionTemplateLiteral(node.initializer))
  ) {
    const oldValue = node.initializer.text;
    const newValue = accentText(oldValue);
    if (newValue !== oldValue) {
      edits.push({
        start: node.initializer.getStart(sourceFile),
        end: node.initializer.end,
        value: JSON.stringify(newValue),
      });
    }
  }

  ts.forEachChild(node, visit);
};

visit(sourceFile);

let output = sourceText;
for (const edit of edits.sort((a, b) => b.start - a.start)) {
  output = output.slice(0, edit.start) + edit.value + output.slice(edit.end);
}

fs.writeFileSync(filePath, output);
console.log(`Updated ${edits.length} text fields in ${filePath}`);
